//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warder.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Levels
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int Access_Level_ID { get; set; }
    
        public virtual Access_levels Access_levels { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
